version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    volumes:
      - ./:/app

  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: GetnowX
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - getnowx_practice:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  getnowx_practice:
